In [1]:
import torch

## Tensor attributes

In [3]:
f32_tensor = torch.tensor([1,2,3,4,5], 
                          dtype=torch.float32,
                          device=None,
                          requires_grad=False
                         )

In [4]:
f32_tensor

tensor([1., 2., 3., 4., 5.])

In [5]:
f16_tensor = f32_tensor.type(torch.float16)
f16_tensor

tensor([1., 2., 3., 4., 5.], dtype=torch.float16)

In [10]:
x = f32_tensor * f16_tensor
x, x.dtype

(tensor([ 1.,  4.,  9., 16., 25.]), torch.float32)

In [12]:
x[:, None]

tensor([[ 1.],
        [ 4.],
        [ 9.],
        [16.],
        [25.]])

In [16]:
y = f32_tensor.type(torch.int32) * f16_tensor.type(torch.int32)
y, y.dtype

(tensor([ 1,  4,  9, 16, 25], dtype=torch.int32), torch.int32)

## Torch Cuda

In [19]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [20]:
f32_tensor_cuda = torch.tensor([1.2, 34.4, 56.23], device=device)

In [21]:
f32_tensor_cuda

tensor([ 1.2000, 34.4000, 56.2300], device='cuda:0')

## Manipulating Tensors (tensor operations)
**Tensor operations** :
* Addition
* Substraction
* Multiplication (element wise)
* Division
* Matrix multiplication

In [22]:
A = torch.tensor([1,2,3])
A

tensor([1, 2, 3])

In [23]:
A + 10

tensor([11, 12, 13])

In [24]:
A * 10

tensor([10, 20, 30])

In [25]:
A/10

tensor([0.1000, 0.2000, 0.3000])

In [26]:
A = torch.tensor(
    [
        [1,2,3], 
        [4,5,6]
    ]
)
B = torch.tensor(
    [
        [7,8,9],
        [11,12,13]
    ]
)

In [27]:
A * B

tensor([[ 7, 16, 27],
        [44, 60, 78]])

In [28]:
A @ B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [29]:
A @ B.T

tensor([[ 50,  74],
        [122, 182]])

In [30]:
B @ A.T

tensor([[ 50, 122],
        [ 74, 182]])

In [31]:
B.T @ A

tensor([[ 51,  69,  87],
        [ 56,  76,  96],
        [ 61,  83, 105]])

In [32]:
torch.add(A, 20)

tensor([[21, 22, 23],
        [24, 25, 26]])

In [33]:
torch.mul(B, 2)

tensor([[14, 16, 18],
        [22, 24, 26]])

In [35]:
torch.matmul(A, B.T)

tensor([[ 50,  74],
        [122, 182]])